### PR TITLE
Provide a sass import for Tachyons colors

### PR DESCRIPTION
**Pull request by justin808**
Committing the built file tachyons-colors-variables.scss because of
https://github.com/npm/npm/issues/3055

### CODE REVIEW

**Comment by joelhooks** [comment]
We will prefer to maintain these manually.

**Review by joelhooks — APPROVED** [review]

**Comment by joelhooks** [comment]
@justin808 took some more time to fully understand and appreciate this solution. Sorry for being so dismissive. It's a better interim solution for sure.

**Comment by justin808** [comment]
Want me to push this to egghead-tachyons-colors on npm? and revert my revert in my branch?

**Comment by joelhooks** [comment]
can we just target the github repo for now?

**Comment by trevordmiller** [comment]
`tachyons-egghead` is just using this repo directly currently:
https://github.com/eggheadio/tachyons-egghead/blob/master/package.json#L29
I would leave it this way as that is how all the other egghead forked tachyons modules are being referenced.

@justin808 If you'll test that this wont break tachyons-egghead, that's great - but I don't think the tachyons-egghead build supports scss currently. To test,
- In a new branch in [`tachyons-egghead`](https://github.com/eggheadio/tachyons-egghead), run `yarn` so the `tachyons-colors` dependency gets updated to the latest from this PR; it may not recognize the change since this PR doesn't have a tag, so you may need to push a new tag
- Push your branch
- Run `yarn bump` and answer the question about what the new version should be, which will push a new package.json version and git tag for `tachyons-egghead` and will trigger a new `css` folder build and package publish on npm: https://github.com/eggheadio/tachyons-egghead
- Upgrade a project using `tachyons-egghead` to this new version ^ and ensure it still works

You can also test these things locally with yarn link before you publish: https://yarnpkg.com/lang/en/docs/cli/link/

**Comment by justin808** [comment]
@trevordmiller:

> @justin808 If you'll test that this wont break tachyons-egghead, that's great - but I don't think the tachyons-egghead build supports scss currently. 

The source to tachyons-egghead uses the CSS file directly. The sass file an output of my changes. I didn't change the CSS file.

I will still do the test steps if you think it's necessary.

**Comment by trevordmiller** [comment]
@justin808 Ok don't worry about it then. We'll find out the next time someone bumps tachyons-egghead, but it sounds like it shouldn't be a problem. Thanks.

**Comment by justin808** [comment]
@trevordmiller we might not need to have the generated file checked in. Shall I create a npm module for this, or do you want to? We should try without the generated file and see if it's built automatically when publishing. https://github.com/eggheadio/tachyons-colors/blob/master/tachyons-colors-variables.scss

**Comment by trevordmiller** [comment]
@justin808 I would recommend just sticking with the github references since all the other egghead tachyons forks do that; see here: https://github.com/eggheadio/tachyons-egghead/blob/master/package.json#L16-L67

**Comment by justin808** [comment]
@trevordmiller Then we need to be sure to run that script and check in the updated file when we change colors.

**Comment by trevordmiller** [comment]
@justin808 Yeah that's how all the forked modules work. So you'll need to remove the `css` line you added to the `.gitignore`.

**Comment by justin808** [comment]
> So you'll need to remove the css line you added to the .gitignore.

@trevordmiller the css line is for the css directory that gets created if you want to run `yarn build`. It has nothing to do with other files. If you want to exclude *.css files, you have to put in *.css.

**Pull request merged**
